FILE_ESEGUIBILE=src
FILE_FUNZIONI=functions


all: $(FILE_ESEGUIBILE)

$(FILE_ESEGUIBILE): $(FILE_ESEGUIBILE).o $(FILE_FUNZIONI).o
	gcc -o $(FILE_ESEGUIBILE) $(FILE_ESEGUIBILE).o $(FILE_FUNZIONI).o
	
$(FILE_ESEGUIBILE).o: $(FILE_ESEGUIBILE).c $(FILE_FUNZIONI).h
	gcc -c $(FILE_ESEGUIBILE).c
	
$(FILE_FUNZIONI).o: $(FILE_FUNZIONI).c $(FILE_FUNZIONI).h
	gcc -c $(FILE_FUNZIONI).c

clean:
	rm src $(FILE_ESEGUIBILE).o $(FILE_FUNZIONI).o
